language: ruby

services:
  - docker

# test build
before_install:
  - docker build -t proxy-testing ./proxy
  - docker build -t api-testing -f ./backend/Dockerfile.dev ./backend
  - docker run -d --name api-testing api-testing
  - docker -v
  - docker ps -a

# run tests
before_script:
  # FIXME: nginx config test failing
  # - docker run -t proxy-testing /bin/sh -c "nginx -vtc /etc/nginx/conf.d/default.conf;"
  - docker exec api-testing /bin/sh -c "cd /usr/src/app && python -m pytest -v;"

# production build
script:
  # nginx reverse proxy
  - docker build -t roblobob/passphrases-proxy:$TRAVIS_COMMIT ./proxy
  - docker build -t roblobob/passphrases-proxy:latest ./proxy

  # python flask api
  - docker build -t roblobob/passphrases-api:$TRAVIS_COMMIT -f ./backend/Dockerfile.gunicorn ./backend
  - docker build -t roblobob/passphrases-api:latest -f ./backend/Dockerfile.gunicorn ./backend

  # node nextjs frontend
  - docker build -t roblobob/passphrases-frontend:$TRAVIS_COMMIT ./frontend
  - docker build -t roblobob/passphrases-frontend:latest ./frontend

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master

