language: ruby

services:
  - docker

# test build
before_install:
  - docker build -t proxy-testing ./proxy/Dockerfile
  - docker build -t api-testing ./backend/Dockerfile.dev
  - docker run -d api-testing
  - docker -v
  - docker ps -a

# run tests
before_script:
  - docker run -t proxy-testing /bin/sh -c "/usr/bin/nginx -v -t -V -c /etc/nginx/conf.d/default.conf;"
  - docker exec api-testing /bin/sh -c "cd /usr/src/app && python -m pytest;"

# production build
script:
  - docker build -t roblobob/devops-passphrases-proxy ./proxy/Dockerfile
  - docker build -t roblobob/devops-passphrases-api ./backend/Dockerfile.gunicorn
  - docker build -t roblobob/devops-passphrases-frontend ./frontend/Dockerfile
# push to docker hub
# after_script:


