version: "3.9"
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "5050:80"

  api:
    build:
      dockerfile: Dockerfile.gunicorn
      context: ./flask
    environment:
      PORT: 8000

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      PORT: 3000

