version: "3.9"
services:
  proxy:
    build:
    dockerfile: Dockerfile
    context: ./proxy
    ports:
      - "5050:80"

  api:
    build:
      dockerfile: Dockerfile.gunicorn
      context: ./backend
    environment:
      PORT: 8000

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    environment:
      PORT: 3000

