version: "3.8"
services:
  gunicorn:
    build:
      dockerfile: Dockerfile.gunicorn
      context: .
    environment:
      PORT: 8000

  nginx:
    build:
      dockerfile: Dockerfile.nginx
      context: .
    environment:
      APP: gunicorn
    ports:
      - 4444:80
