FROM python:3-alpine

ENV PORT 80
ENV WORKERS 4

WORKDIR /app
RUN apk add git
COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install gunicorn
COPY . .
RUN git clone https://github.com/robinedmunds/Command-line-Passphrase-Generator.git business

CMD cd /app && gunicorn --workers=$WORKERS --bind=0.0.0.0:$PORT ".:app"
