import { useEffect, useState } from "react"
import type { NextPage } from 'next'
import Head from 'next/head'
import axios from "axios"
import Container from '@mui/material/Container'
import Stack from '@mui/material/Stack'
import Button from '@mui/material/Button'
import Phrases from '../components/phrases'

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState(true)
  const [phrases, setPhrases] = useState([])

  const fetchPhrases = () => {
    axios.get("//docker.local:4444/diceware/?format=json&phrase_count=10&word_count=4&separator= &wordlist=eff_short_wordlist_1.txt")
      .then(res => {
        setPhrases(res.data.phrases.phrases.map(obj => obj.phrase))
        setIsLoading(false)
      })
  }

  useEffect(() => {
    fetchPhrases()
  }, [])

  const renderPhrases = () => {
    if (isLoading) return <p>Loading...</p>
    return <Phrases phrases={phrases} />
  }

  return (
    <>
      <Head>
        <title>passphrases</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <h1>Passphrases</h1>
        <h2>Generate strong, memorable and easy-to-type passphrases.</h2>

      <Stack spacing={2} direction="row">
        <Button onClick={() => {fetchPhrases()}} variant="contained">Generate</Button>
      </Stack>

        {renderPhrases()}
      </Container>
    </>
  )
}

export default Home
