import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>passphrases</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="">
        <h1>passphrases</h1>
      </div>
    </>

  )
}

export default Home
