FROM python:3-alpine

ENV PORT 8000
ENV WORKERS 4

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .

CMD gunicorn --workers=$WORKERS --bind=0.0.0.0:$PORT django_project.wsgi:application
