FROM python:3-alpine

ENV PORT 8000

WORKDIR /app
RUN apk add git
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
RUN git clone https://github.com/robinedmunds/Command-line-Passphrase-Generator.git business

CMD flask --app api --debug run --host=0:$PORT
